import iPhone from "../assets/images/img1.jpeg";
import Screen from "../assets/images/img2.jpeg";
import HeadSet from "../assets/images/img3.png";


const metaDataList = [
   {
      name: "iPhone 14",
      image: { iPhone },
      description: "The extraordinary battery life, lightweight design, pro-level camera and video features, groundbreaking safety capabilities like Emergency SOS via satellite, and all iOS 16 has to offer make iPhone 14 a great option for anyone in the market for a new iPhone."
   },

   {
      name: "LG Display Monitor",
      image: { Screen },
      description: "A monitor is an electronic output device that is also known as a video display terminal (VDT) or a video display unit (VDU). It is used to display images, text, video, and graphics information generated by a connected computer via a computer's video card."
   },

   {
      name: "Cool HeadSet",
      image: { HeadSet },
      description: "A headset is a combination of a microphone and headphones. A headset makes spoken communication possible without having to wear an earpiece or hold a microphone. It replaces, for example, a telephone handset and can be used to talk and listen at the same time."
   }
]

export default metaDataList;